input:
  resource: raw_aws_route53_input

pipeline:
  processors:
    - mapping: from "route53.blobl"
    # This switch checks for the ocsf_topic metadata and if it exists applies additional mapping if not it deletes the log.
output:
  resource: ocsf_kafka_output